### PR TITLE
[ENG-5994] Fix Preprint Resubmission Workflow

### PR DESCRIPTION
**Pull request by uditijmehta**
-   Ticket: [https://openscience.atlassian.net/browse/ENG-5994]
-   Feature flag: n/a

## Purpose

Fix Preprint Resubmission Workflow

## Summary of Changes

Non-ACCEPTED preprints in edit mode are resubmitted to moderation.

### CODE REVIEW

**Review by brianjgeiger — COMMENTED** [review]
I wonder if this logic can be simplified. Maybe on the outside of the loop if it were `if (this.provider.reviewsWorkflow && this.preprint.reviewsState !== ReviewsState.Accepted)`. I'm not positive, but you might be able to collapse it to two states then. Worth giving it a think; this is very complicated.

**Review by cslzchen — APPROVED** [review]
LGTM 🎆 . (Update: feature verified locally after I got `reviews` working)

@brianjgeiger should this be a hotfix, target a B&I branch or merge into develop?

**Comment by brianjgeiger** [comment]
@cslzchen If you or Yuhuai are up for it, I'd say a hotfix, since it's affecting Prod capability to resubmit preprints. We can test it on staging2. I'll put the branch up now.

**Comment by cslzchen** [comment]
Sounds good! I see it's already being deployed to staging2. I will inform QA and once it's approved I will hotfix this one. @mfraezz heads-up.

**Comment by cslzchen** [comment]
Commits cherry-picked into the `hotfix/24.07.1`, consider PR merged.

**Pull request closed without merging**
