### PR TITLE
[ENG-2898] Revert license & nodeLicense validations updates + fixes

### PR DESCRIPTION
**Pull request by fabmiz**
- Ticket: [ENG-2898]
- Feature flag: n/a

## Purpose

Fix issues with validating draft/registration license/nodeLicense.

## QA Notes

[ENG-2898]: https://openscience.atlassian.net/browse/ENG-2898

### CODE REVIEW

**Review by futa-ikeda — CHANGES_REQUESTED** [review]
I've checked this out locally and have noticed that when I load into a draft that has `MIT License` selected, it will have the text boxes for Year and Copyright Holder shown.

**Comment by fabmiz** [comment]
> I've checked this out locally and have noticed that when I load into a draft that has `MIT License` selected, it will have the text boxes for Year and Copyright Holder shown.

🤔 MIT License does have these required fields. see https://api.osf.io/v2/licenses/563c1cf88c5e4a3877f9e972/

**Comment by futa-ikeda** [comment]
> > I've checked this out locally and have noticed that when I load into a draft that has `MIT License` selected, it will have the text boxes for Year and Copyright Holder shown.
> 
> 🤔 MIT License does have these required fields. see https://api.osf.io/v2/licenses/563c1cf88c5e4a3877f9e972/

🤦  I goofed. Had assumed that it didn't.

**Review by futa-ikeda — APPROVED** [review]
Code looks good and checked it out locally and looks good there too 🚀

**Review by adlius — APPROVED** [review]

**Pull request merged**
