### PR TITLE
[ENG-5028] [ENG-5919] Preprints Affiliation Project PR (FE)

### PR DESCRIPTION
**Pull request by bp-cos**
-   Ticket: [ENG-5919]
-   Feature flag: n/a

## Purpose

Request to merge the feature/preprints-affiliations branch into develop for release.

## Summary of Changes

Merge all the feature work into the develop branch

[ENG-5919]: https://openscience.atlassian.net/browse/ENG-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by brianjgeiger — CHANGES_REQUESTED** [review]
The most minor of changes to some tests, otherwise looks good.

**Comment by brianjgeiger** [comment]
Looks like there were some [unintended changes to the developer apps page](https://percy.io/Center-for-Open-Science/ember-osf-web/builds/36410790/changed/1990360498?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&utm_source=github_status_public&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280) that will need to be corrected.

**Comment by cslzchen** [comment]
It seems the new changes come from last weeks hotfix: https://percy.io/Center-for-Open-Science/ember-osf-web/builds/36384644/changed/1989532351?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&utm_source=github_status_public&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280.

Maybe taking a look with @futa-ikeda to see if they can be dismissed/manually approved.

**Comment by cslzchen** [comment]
Oh, it's not from the hotfix, it's our `develop` branch has an issue

Screenshot 2024-09-17 at 12 32 31
Screenshot 2024-09-17 at 12 32 43

And the history showed that last FE release also had 3 percy issues and two recent merge into develop increase that to 14 and this PR increases that change to 17.

Screenshot 2024-09-17 at 12 37 00
Screenshot 2024-09-17 at 12 37 08
Screenshot 2024-09-17 at 12 37 18

**Review by brianjgeiger — APPROVED** [review]

**Pull request merged**
